###
### Go sequentially through points 1) .. 4) to set the basic variables:
###

log:
  to_console: True
  to_file: True
  file_path: 'miio2mqtt.log'

system:
  idle: 30

mqtt:

###
### 1) Update IP address and port of your MQTT broker
###

  host:
    address: "127.0.0.1"
    port: 1883
    keepalive: 60

###
### 2) If your MQTT broker uses authorization, uncomment and edit the following
###    'auth' section

# auth:
#   username: <username>
#   password: <password>

  client:
    id: "miio2mqtt"

  publish:
    qos: 1
    retain: False

  subscribe:
    qos: 1

### 
### 3) Get information about your Xiaomi devices:
###      https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor
###
### 4) Update 'devices' section below.
###
###

devices:

    # - name
    #   - custom name of device
    #   - name must satisfy the rules for Python variables:
    #     - name must start with a letter or the underscore character
    #     - name cannot start with a number
    #     - name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
    #     - names are case-sensitive (age, Age and AGE are three different variables)
    # - ip
    #   - copied from Xiaomi-cloud-tokens-extractor
    # - token
    #   - copied from Xiaomi-cloud-tokens-extractor
    # - model
    #   - copied from Xiaomi-cloud-tokens-extractor
    
  - name: myDeviceName1
    ip: 192.168.1.100
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    model: model.of.device1

  - name: myDeviceName2
    ip: 192.168.1.101
    token: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    model: model.of.device2
